version: 2

shared: &shared
  working_directory: ~/graphflow

  steps:
    - checkout

    - run:
        name: Apt Install
        command: |
          sudo apt-get -y update
          sudo apt-get install -y libc6
          sudo apt-get install -y g++

    - run:
        name: Installing Packages
        command: |
          pip install --upgrade --user pip
          pip install --upgrade --user .
          CC=gcc python setup.py build_ext --inplace

    - run:
        name: Run Unit Tests
        command: |
          pip install --upgrade --user .[test]
          pytest --doctest-cython


jobs:

  py38:
    <<: *shared
    docker:
      - image: cimg/python:3.8

  py39:
    <<: *shared
    docker:
      - image: cimg/python:3.9

  py310:
    <<: *shared
    docker:
      - image: cimg/python:3.10

  py311:
    <<: *shared
    docker:
      - image: cimg/python:3.11

  py312:
    <<: *shared
    docker:
      - image: cimg/python:3.12

workflows:
  version: 2
  build:
    jobs:
      - py38
      - py39
      - py310
      - py311
      - py312
