version: 2

shared: &shared
  working_directory: ~/graphflow

  steps:
    - checkout

    - run:
        name: Apt Install
        command: |
          sudo apt-get update
          sudo apt-get install libc6
          sudo apt-get install gfortran

    - run:
        name: Installing Packages
        command: |
          pip install --upgrade --user pip
          pip install --upgrade --user numpy
          pip install --upgrade --user pandas
          pip install --upgrade --user Cython
          pip install --upgrade --user .
          pip install --upgrade --user unittest2
          pip install --upgrade --user pytest

    - run:
        name: Run Unit Tests
        command: |
          pytest



jobs:
  py35:
    <<: *shared
    docker:
      - image: circleci/python:3.5

  py36:
    <<: *shared
    docker:
      - image: circleci/python:3.6

  py37:
    <<: *shared
    docker:
      - image: circleci/python:3.7

  py38:
    <<: *shared
    docker:
      - image: circleci/python:3.8

  py39:
    <<: *shared
    docker:
      - image: circleci/python:3.9

workflows:
  version: 2
  build:
    jobs:
#      - py35
#      - py36
#      - py37
      - py38
#      - py39
